# Site
name: "航通社"
title: "航通社"
description: "你应该知道的历史、现在和未来"
url: "https://lishuhang.me"
domain: lishuhang.me
email: i@lishuhang.me

lang: zh

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  posts:
    permalink: /posts/:year/:month/:day/:title/
    output: true

color: "#347df8"

authors:
  james:
    name: James Li
    display_name: James
    email: i@lishuhang.me
    web: https://lishuhang.me
    description: "书航，航通社创始人"

