domain: lishuhang.me
url: https://lishuhang.me/
baseurl: "/"

title: 航通社
email: i@lishuhang.me
author: Shuhang Li

lang: zh

plugins:
  - jekyll-seo-tag



collections:
  posts:
    permalink: /posts/:year/:month/:day/:title/
    output: true

color: "#347df8"
disqus:
  shortname: lishuhang

rrss:
  email: "mailto:i@lishuhang.me"
  telegram: "https://t.me/lishuhang"
  facebook: "https://facebook.com/lishuhang"
  instagram: "https://instagram.com/lishuhang"
  twitter: "https://x.com/lishuhang"
  discord: ""
  linkedin: "https://www.linkedin.com/in/lishuhang/"
  whatsapp: ""
  pinterest: ""
